config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :dogs

  root 'dogs#index'
end

app/models/dog.rb
class Dog < ActiveRecord::Base
    attr_accessible :title, :description, :breed #idk
	belongs_to :user

	has_attached_file :image,styles: {medium: "300x300"}
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	has_attached_file :document
	validates_attachment :document, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :dogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
	before_action :find_dog, only: [:show, :edit, :update, :destroy]


	def index
		@dogs = Dog.all.order("created_at DESC")
	end

	def new
		@dog=current_user.dogs.build
	end

	def show
	end

	def edit
	end

	def update
		if @dog.update(dog_params)
			redirect_to @dog, notice: " You have succesfully updated the dog information"
		else
			render 'edit'
		end
	end

	def destroy
		@dog.destroy
		redirect_to root_path
	end


	def create
		@dog =current_user.dogs.build(dog_params)
		if @dog.save
			redirect_to @dog, notice: " You have succesfully added the Dog"
		else
			render 'new'
		end
	end


	private

	def dog_params
		params.require(:dog).permit(:title,:description,:image,:document)
	end



	def find_dog
		@dog = Dog.find(params[:id])
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.haml
= simple_form_for @dog, html: { multipart: true } do |f|
	- if @dog.errors.any?
		#errors
			%h2
				= pluralize(@dog.errors.count, "error")
				prevented this dog from saving
			%ul
				- @dog.errors.full_messages.each do |msg|
					%li= msg

	.form-group
		= f.input :image, input_html: { class: 'form-control' }

	.form-group
		= f.input :title, input_html: { class: 'form-control' }

	.form-group
		= f.input :description, input_html: { class: 'form-control' }

	.form-group
		= f.input :document, input_html: { class: 'form-control' }


	= f.button :submit, class: "btn btn-primary"

app/views/dogs/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Edit Your dog
			.panel-body
				.current_image
					%strong.center Current Image
					= image_tag @dog.image.url(:medium)
				= render 'form'

app/views/dogs/index.html.haml
- @dogs.each do |dog|
	.jumbotron
		.container
			= link_to (image_tag dog.image.url(:medium)), dog
			%h2= link_to dog.title, dog
			

app/views/dogs/new.html.haml
.col-md-6.col-md-offset-3
	.row
		.panel.panel-default
			.panel-heading
				%h1 Enter a new dog
			.panel-body
				= render 'form'

app/views/dogs/show.html.haml
%center
	= image_tag @dog.image.url(:medium)
	%h1= @dog.title
	%p= @dog.description
	%br
	= @dog.document.url

	Entered by 
	= @dog.user.email
	%br
	= link_to "Back",root_path , class: "btn btn-default"
	= link_to "Edit", edit_dog_path, class: "btn btn-warning"
	= link_to "Delete", dog_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"
	%br
	%center
		Entered by 
		= @dog.user.email
		%br
		Created on
		= @dog.user.created_at
		%br
		Updated on
		= @dog.user.updated_at
		

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dogswhocode</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
%html
%head
	%title Dogs Who Code
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags

%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand= link_to "Dogs Who Code", root_path

			-if user_signed_in?
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "Enter a new dog", new_dog_path
					%li= link_to "Account", edit_user_registration_path
					%li= link_to "Sign Out", destroy_user_session_path, method: :delete
			-else
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "Sign Up", new_user_registration_path
					%li= link_to "Sign In", new_user_session_path
	.container
	- flash.each do |name,msg|
		= content_tag :div, msg, class:"alert alert-info"
	= yield